name: rp_mobile
description: RP Mobile

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bloc: ^3.0.0  # ^2.0.0  19/03/2020   
  flutter_bloc: ^3.2.0 #^2. 0.0   19/03/2020
  hydrated_bloc:   ^3.0.0 # ^2.0.0 19/03/2020
  equatable: ^1.0.1
  intl:
  intl_translation:
  hive:
  hive_flutter:
  division: ^0.8.5
  cached_network_image: ^2.0.0-rc
  dio: ^3.0.7
  optional: ^3.1.0
  get_it: ^3.1.0
  rxdart:   ^0.23.1 # ^0.22.6  19/03/2020
  qr_flutter: ^3.1.0
  expandable: ^3.0.1
  webview_flutter: ^0.3.17
  yandex_mapkit:
    path: ./yandex_mapkit
  permission_handler: '^4.0.0'
  location: ^2.3.5
  url_launcher: ^5.4.1
  open_appstore: ^1.0.2
  flutter_appavailability:
    git:
      url: "https://github.com/pichillilorenzo/flutter_appavailability.git"
      ref: "7550417da035bfa53d131cf914b50249807108e8"
  sliding_sheet: ^0.2.4
  sliding_up_panel: ^1.0.0
  shared_preferences: ^0.5.6
  android_intent: ^0.3.5
  solid_bottom_sheet: ^0.1.9
  date_range_picker: ^1.0.6
  carousel_slider: ^1.4.1
  firebase_crashlytics:
  firebase_analytics:
  image_picker:
  image_cropper:
  path_provider:
  path: 



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  mockito: ^4.1.1
  bloc_test:  ^4.0.0     # ^2.2.2  19/03/2020
  source_gen:
  json_models_generator:
    path: json_models_generator


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - images/mock_images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf

    - family: Open Sans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700

        - asset: fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800

        - asset: fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic

        - asset: fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300

        - asset: fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Open_Sans/OpenSans-Regular.ttf

        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600

        - asset: fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: PT Russia Text
      fonts:
        - asset: fonts/PT_Russia_Text/PT_Russia_Text-Regular.ttf
          weight: 400

        - asset: fonts/PT_Russia_Text/PT_Russia_Text-Medium.ttf
          weight: 500

        - asset: fonts/PT_Russia_Text/PT_Russia_Text-DemiBold.ttf
          weight: 600

        - asset: fonts/PT_Russia_Text/PT_Russia_Text-Bold.ttf
          weight: 700

        - asset: fonts/PT_Russia_Text/PT_Russia_Text-Black.ttf
          weight: 800

    - family: Golos
      fonts:
        - asset: fonts/Golos/Golos_Text_Bold.ttf
          weight: 700

        - asset: fonts/Golos/Golos_Text_DemiBold.ttf
          weight: 600

        - asset: fonts/Golos/Golos_Text_Medium.ttf
          weight: 500

        - asset: fonts/Golos/Golos_Text_Regular.ttf
          weight: 400

