/// Flutter icons AppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData check_mark = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData eye_off = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData rounded_arrow_left = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData qr = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData question = const IconData(0xe808, fontFamily: _kFontFam);

}
